excluded:
  - Pods
disabled_rules:
  - superfluous_disable_command
  - force_unwrapping
  - force_cast
  - force_try
opt_in_rules:
  - array_init
  - multiline_arguments
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - static_operator
  - last_where
  - discouraged_optional_boolean
  - convenience_type
  - closure_body_length
  - closure_end_indentation
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_collection
  - first_where
  - sorted_first_last
  - legacy_random
  - literal_expression_end_indentation
  - private_outlet
  - modifier_order
  - empty_count
  - empty_string
  - redundant_type_annotation
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  - unused_import
  - discouraged_object_literal
attributes:
  always_on_same_line: []
  always_on_line_above: []
switch_case_alignment:
  indented_cases: true
line_length:
  error: 120
identifier_name:
  excluded:
    - id
    - db
reporter: "xcode"
